### ISSUE TITLE
Unable to get IClaimsTransformation to work with HttpSysListener

### ISSUE THREAD

**Issue by ducman** [aspnet/HttpSysServer#389]
The new core 2.0 way of doing claims transformation doesn't seem to work when doing a `dotnet run` with `UseHttpSys`. It **does work** when running via IIS Express. It also work with the old `WebListener` but claims transformation was done via middleware in core 1.* (so may be a mute point).

I was able to reproduce this with the default windows authentication core web project template. Here is my `UseHttpSys`:
```
.UseHttpSys(options =>
{
    options.Authentication.Schemes = AuthenticationSchemes.Negotiate;
    options.Authentication.AllowAnonymous = false;
})
```

And the transform sample:
```
public Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
{
    var identity = principal.Identities.FirstOrDefault();
    if (identity != null)
    {
        identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, "123"));
        identity.AddClaim(new Claim(ClaimTypes.Email, "blah@blah.com"));
    }
    return Task.FromResult(principal);
}
```

Please let me know if I'm missing some configuration.

**Comment by Tratcher** [comment]
How to you consume the identity? It's likely that claims transformation isn't running because you haven't asked it to.

**Comment by ducman** [comment]
If I use `UseKestrel` and launch using IIS Express (from VS), I can see that an `AuthenticateAsync` is being called which in turn called `TransformAsync` (line 71 @ [AuthenticationService](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationService.cs)). From the call stack, it seem IIS integration middleware is requesting the `AuthenticateAsyc'. I'm guessing HttpSysListener isn't doing this? I'm sorry, I'm not familiar with much of this.

All I know is if I use kestrel with iis express, my claim transformation get instantiated; but using http sys, it doesn't. No other code is changed to switch between kestrel and http sys.

**Comment by Tratcher** [comment]
Ok, that makes sense. IIS does this: https://github.com/aspnet/IISIntegration/blob/cc31406913ae349a6f69acef65be65da91086b39/src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs#L114

HttpSys doesn't because it starts with the identity https://github.com/aspnet/HttpSysServer/blob/dev/src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/Request.cs#L84.

To make claims transformation run you either need to call `httpContext.AuthenticateAsync(HttpSysDefaults.AuthenticationScheme);` or you put `app.UseAuthentication()` in your pipeline and specify HttpSysDefaults.AuthenticationScheme as hour default auth scheme (e.g. `services.AddAuthentication(HttpSysDefaults.AuthenticationScheme)`).

**Comment by ducman** [comment]
I have added what you have suggested and it works. Thank you.

**Comment by billwolckenlmco** [comment]
@ducman Since @Tratcher had two suggestions (calling AuthenticateAsync or setting HttpSys as the default scheme), which one did you add which worked?

I'm in a similar situation, however I have HttpSys configured to allow anonymous as well as Basic auth:

    .UseHttpSys(options =>
    {
        options.Authentication.Schemes = AuthenticationSchemes.Negotiate | AuthenticationSchemes.Basic;
        options.Authentication.AllowAnonymous = true;
    })

I followed the suggestion above:

    ...
    services.AddAuthentication(HttpSysDefaults.AuthenticationScheme);
    services.AddSingleton<IClaimsTransformation, MyClaimsTransformation>();
    ...

And I have a controller method decorated with `[Authorize]` which outputs all the claims to the page.  The Authorize attribute does cause auth to take place, since within the controller method User is set to a WindowsPrincipal and I get the list of claims I'd expect from it.  An instance of MyClaimsTransformation gets created, but its TransformAsync is never called.  When I try adding `await this.httpContextAccessor.HttpContext.Authentication.AuthenticateAsync(HttpSysDefaults.AuthenticationScheme);` in the controller method (just to test - it can't live there for real), I get "InvalidOperationException: No authentication handler is configured to authenticate for the scheme: Windows".  

Similar to the ducman, MyClaimsTransformation.TransformAsync was being called before I switched to HttpSys (so when I was running under IIS Express and I was using `services.AddAuthentication(IISDefaults.AuthenticationScheme)`.

**Comment by billwolckenlmco** [comment]
The problem in my case was that I was missing `app.UseAuthentication()` in Configure().  Evidently (and I want to learn more about the implementation of ASP.NET Core to understand why) that is not required for the Authorize attribute to cause a 401 challenge with IIS or HttpSys, but is required for any additional auth processing such as claims transformation.

**Comment by ducman** [comment]
Glad you figured it out. I went with the same approach.

**Comment by PaulAngelino** [comment]
Hello @ducman and @billwolckenlmco.  I'm having the exact same problem you two describe here.  I have a custom IClaimsTransformation implementation which was working fine before I switched to using HTTP.sys, and now the TransformAsync method never gets called.  I was optimistic upon reading this post, but I'm still not able to get this working after trying what you suggest.  I have added `services.AddAuthentication(HttpSysDefaults.AuthenticationScheme)` to `ConfigureServices()` and `app.UseAuthentication()` to `Configure()`.  Do you have any other suggestions as to what I can try or why I still can't get this to work?

**Comment by PaulAngelino** [comment]
Furthermore, I am able to call `HttpContext.AuthenticateAsync(HttpSysDefaults.AuthenticationScheme)`, which I'm currently doing in the Index method of my Home controller just for testing.  I see TransformAsync get called and the expected role get added as a claim to the principal, but now the Authorize attribute on my secured controller method is not working as expected.  Again, this is something that worked properly before I was using HTTP.sys.  The role that is added to the principal in TransformAsync should give the user access to the secured controller method, but authorization is failing for the request.  Specifically, I have this in ConfigureServices:

```
services.AddAuthorization(options =>
{
    options.AddPolicy("AdminsOnly", policy => policy.RequireClaim(ClaimTypes.Role, "auth_role"));
});
```

and then my controller method looks like this:

```
[Authorize(Policy = "AdminsOnly")]
public IActionResult AuthPage()
{
    return View();
}
```

**Comment by ducman** [comment]
In core 2.0, you have to inject the IClaimsTransformation. We didn't had to do this in 1.* since it was a middleware. I'm hoping this is what you're missing.

```
services.AddScoped<IClaimsTransformation, MyClaimsTransformation>();
```

**Comment by PaulAngelino** [comment]
Ok, I figured out my problem.  There was a piece of this that came over from previous work I had done with Identity Framework and trying to get that working with various authentication schemes.  I already had an `IUserClaimStore` implementation with the `GetClaimsAsync` method that was retrieving the user roles from the database.  When I switched over to trying to get the `IClaimsTransformation` working just for authorization, I brought that `IUserClaimStore` class into the project and was calling it from the `TransformAsync` method within my `IClaimsTransformation` implementation.  In order to get the `IUserClaimStore` into the pipeline, I was doing this in `ConfigureServices`:

```
services.AddIdentity<AuthorizationService.IdentityUser, IdentityRole>()
    .AddUserStore<UserClaimStore>();
```
and then in my `TransformAsync()` I was calling the `GetClaimsAsync` method of the `UserManager` class, which in turn would call `UserClaimStore.GetClaimsAsync()`.

I have now ditched Identity Framework completely for this use case.  I brought the code from my old `GetClaimsAsync` method into the `ClaimsTransformer`, and now everything is working as expected.  As per the suggestions from others here, adding `services.AddAuthentication(HttpSysDefaults.AuthenticationScheme)` into `ConfigureServices` and `app.UseAuthentication()` into `Configure` now causes `TransformAsync` to be invoked when authorization is being checked.

**Comment by burzyk** [comment]
I also had a similar problem with the `IClaimsTransformation` not being called. I tried everything mentioned above, but what did the trick was to put the `UseAuthentication` before all other middlewares (`UseMvc` in particular).
In retrospect I can understand why this is happening, but I'm leaving this for any other lost soul that could have this problem.
