### ISSUE TITLE
Creating a shared sources package between HttpSys and ANCM in-process for native to managed interop

### ISSUE THREAD

**Issue by jkotalik** [aspnet/HttpSysServer#396]
In the prototype for ANCM in-process, @davidfowl and I copied files from HttpSysServer to convert native IIS HttpContext into unsafe managed ones. Classes like [HttpApi.cs](https://github.com/aspnet/HttpSysServer/blob/dev/src/Microsoft.AspNetCore.Server.HttpSys/NativeInterop/HttpApi.cs) and [RequestHeaders.cs](https://github.com/aspnet/HttpSysServer/blob/dev/src/Microsoft.AspNetCore.Server.HttpSys/RequestProcessing/RequestHeaders.cs) can be shared across both implementations. @Tratcher proposed that we create a shared source package between HttpSys and IISIntegration. This would require creating a separate library/package in HttpSys.
/cc @Eilon @muratg @Tratcher @davidfowl

**Comment by Tratcher** [comment]
I expect it to be a shared sources package in the HttpSys repo.

**Comment by Eilon** [comment]
Yeah just shared source is all we want. Do either of these repos depend on each other? If not, we might want to avoid making more dependencies... that's where Common often comes into play (though it does end up being a bit of a dumping ground).

**Comment by Tratcher** [comment]
The layering is reasonable for IISIntegration to depend on HttpSysServer, though there's no dependency currently. IISIntegration already depends on Kestrel which is in the same layer of the build graph as HttpSys.

Trying to move an Http.Sys API shared sources package to Common would make it unnecessarily difficult to maintain and test, you'd be juggling three repos rather than two.

**Comment by Eilon** [comment]
Then that sounds reasonable.
