### ISSUE TITLE
[Question] HttpSysListener.SkipIOCPCallbackOnSuccess

### ISSUE THREAD

**Issue by maxcherednik** [aspnet/HttpSysServer#421]
Is this flag reasonable in here: https://github.com/aspnet/HttpSysServer/blob/231cbffe1a5cc0abce11e2d0685683ed74fc7ad5/src/Microsoft.AspNetCore.Server.HttpSys/NativeInterop/DisconnectListener.cs#L115

What was the bug related to this?

> The reason I am asking is that this flag doesn't correlate to the comment:
> Win8# 559317 fixed a bug in Http.sys's HttpReceiveClientCertificate method.
> Without this fix IOCP callbacks were not being called although ERROR_IO_PENDING was
> returned from HttpReceiveClientCertificate when using the 
> FileCompletionNotificationModes.SkipCompletionPortOnSuccess flag.
> This bug was only hit when the buffer passed into HttpReceiveClientCertificate
> (1500 bytes initially) is too small for the certificate.
> Due to this bug in downlevel operating systems the FileCompletionNotificationModes.SkipCompletionPortOnSuccess
> flag is only used on Win8 and later. 

So assuming there was no bug at all the code should look like this:
```
if (statusCode == UnsafeNclNativeMethods.ErrorCodes.ERROR_SUCCESS)
            {
                // IO operation completed synchronously - callback won't be called to signal completion
                nativeOverlapped.Dispose();
                ConnectionCancellation ignored;
                _connectionCancellationTokens.TryRemove(connectionId, out ignored);
                cts.Cancel();
            } 
```

So why do we have this flag?
Cause before windows 8 the callback was called even if we received ERROR_SUCCESS, but after win 8 it behaves correctly?

**Comment by Tratcher** [comment]
There's an aspect of this you're missing.
https://github.com/aspnet/HttpSysServer/blob/231cbffe1a5cc0abce11e2d0685683ed74fc7ad5/src/Microsoft.AspNetCore.Server.HttpSys/NativeInterop/RequestQueue.cs#L35-L40

When SkipIOCPCallbackOnSuccess is true Http.Sys is configured to disable callbacks for all async operations that complete synch. When it's false the callback is still expected even when the operation completes sync. It's false on Win7 due to a bug in HttpReceiveClientCertificate but the setting can't be changed only for that API, it applies to all callbacks. Heince we check SkipIOCPCallbackOnSuccess and ERROR_SUCCESS after every async call.
